{% set name = "pypcd4" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypcd4-{{ version }}.tar.gz
  sha256: 9785562de694a411151febca2c75e2e1571795adc87800cb26e3d98165286988

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8.2
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.8.2
    - numpy >=1.21.0
    - python-lzf >=0.2.4
    - pydantic >=1.10.8,<=2.6.4

test:
  imports:
    - pypcd4
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Read and write PCL .pcd files in python
  home: https://github.com/MapIV/pypcd4
  license: BSD-3-Clause
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - tetov
